# Generated by Django 3.2.19 on 2023-06-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('valor_comercial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_partida', models.DateField()),
                ('data_chegada', models.DateField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Progresso', 'Progresso'), ('Armazenada', 'Armazenada'), ('Levantada', 'Levantada')], max_length=100)),
                ('criado_por', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categorias Carga',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Remetente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Transportador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
            ],
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='TarifaVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa_carga', to='core.categoriacarga')),
            ],
            options={
                'verbose_name_plural': 'Tarifas por Volume',
            },
        ),
        migrations.CreateModel(
            name='TarifaPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifa_peso', to='core.categoriacarga')),
            ],
            options={
                'verbose_name_plural': 'Tarifas por Peso',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carga')),
            ],
        ),
        migrations.AddField(
            model_name='carga',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rota'),
        ),
        migrations.AddField(
            model_name='carga',
            name='tarifa_peso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarifapeso'),
        ),
        migrations.AddField(
            model_name='carga',
            name='tarifa_volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarifavolume'),
        ),
        migrations.AddField(
            model_name='carga',
            name='viatura_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes_principais', to='core.viatura'),
        ),
        migrations.AddField(
            model_name='carga',
            name='viatura_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportes_secundarios', to='core.viatura'),
        ),
        migrations.AddField(
            model_name='carga',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receptor'),
        ),
        migrations.AddField(
            model_name='carga',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.remetente'),
        ),
        migrations.AddField(
            model_name='carga',
            name='transportador_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes_principais', to='core.transportador'),
        ),
        migrations.AddField(
            model_name='carga',
            name='transportador_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportes_secundarios', to='core.transportador'),
        ),
    ]
