# Generated by Django 3.2.19 on 2023-06-07 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carga',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carga',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rota'),
        ),
        migrations.AddField(
            model_name='carga',
            name='tarifa_peso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarifapeso'),
        ),
        migrations.AddField(
            model_name='carga',
            name='tarifa_volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarifavolume'),
        ),
        migrations.AddField(
            model_name='carga',
            name='viatura_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viatura_principal', to='core.viatura'),
        ),
        migrations.AddField(
            model_name='carga',
            name='viatura_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viatura_secundaria', to='core.viatura'),
        ),
        migrations.AddField(
            model_name='carga',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receptor'),
        ),
        migrations.AddField(
            model_name='carga',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.remetente'),
        ),
        migrations.AddField(
            model_name='carga',
            name='transportador_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportador_principal', to='core.transportador'),
        ),
        migrations.AddField(
            model_name='carga',
            name='transportador_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportador_secundaria', to='core.transportador'),
        ),
    ]
