# Generated by Django 3.2.19 on 2023-06-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Stock-In'), ('OUT', 'Stock-Out')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carga')),
            ],
        ),
        migrations.CreateModel(
            name='CargaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('carga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.carga')),
            ],
        ),
    ]
